version: "3.8"

services:
  application:
    image: spring-boot-mysql-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/sbms?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - springboot-app-data:/app/data
    networks:
      - springboot-db-net

  mysqldb:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbms
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-db-net

networks:
  springboot-db-net:

volumes:
  mysql-data:
  springboot-app-data:
